#-------开发时环境-------#

# 端口号
server:
  port: 8888

# 数据源配置
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&autoReconnect=true
    username: root
    password: 123456

# 配置日志 显示dao执行的sql语句
logging:
  level:
    root: info
    com:
      zwx:
        dao: debug
  file:
    path: log/blog-dev.log